#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Google APIs needed by the Workspace MCP servers (base + MCP services).
GCP_APIS=(
  gmail.googleapis.com
  drive.googleapis.com
  docs.googleapis.com
  sheets.googleapis.com
  calendar-json.googleapis.com
  gmailmcp.googleapis.com
  drivemcp.googleapis.com
  docsmcp.googleapis.com
  sheetsmcp.googleapis.com
  calendarmcp.googleapis.com
)

banner "Google Cloud setup for Workspace MCP"

# ── Stage 1: Preflight ─────────────────────────────────────────────────────
stage "Preflight — Open WebUI URL"
say "This sets up the GCP project + OAuth client that Open WebUI's MCP tool"
say "servers (Gmail, Calendar, Docs, Sheets) authenticate against."
say "Everything happens in the Google Cloud Console with the Google account"
say "that will own the integration — that's you."
note ""
note "Values are written to ${ENV_FILE} in this directory. If that isn't the"
note "deployment's .env, copy the 3 new values to sweetpantedlady's"
note "/opt/docker/composeyourself/.env afterward."
note ""
ask WEBUI_URL "Public Open WebUI URL (e.g. https://ai.example.com):"
WEBUI_URL="${WEBUI_URL%/}"
note ""
note "The OAuth client needs these 4 redirect URIs (Open WebUI's MCP callback"
note "pattern — {WEBUI_URL}/oauth/clients/{connection_id}/callback):"
note "  ${WEBUI_URL}/oauth/clients/mcp:google-gmail/callback"
note "  ${WEBUI_URL}/oauth/clients/mcp:google-calendar/callback"
note "  ${WEBUI_URL}/oauth/clients/mcp:google-docs/callback"
note "  ${WEBUI_URL}/oauth/clients/mcp:google-sheets/callback"
note ""
note "Stage 5 prints these again for copy-paste."
pause

# ── Stage 2: Create the GCP project ───────────────────────────────────────
stage "Create the GCP project"
say "Create a dedicated project (or reuse an existing one)."
open_url "https://console.cloud.google.com/project-create"
step "Log in with the Google account that will own the integration."
step "Project name: e.g. composeyourself-mcp"
step "A billing account must be linked to the project for the APIs to enable."
step "After creation, copy the generated 'Project ID' (not the display name)."
ask GOOGLE_CLOUD_PROJECT "Paste the Project ID:"
write_env GOOGLE_CLOUD_PROJECT "$GOOGLE_CLOUD_PROJECT"

# ── Stage 3: Enable APIs ───────────────────────────────────────────────────
stage "Enable the required Google APIs"

enable_apis_console() {
  say "Enable each of these in the console:"
  open_url "https://console.cloud.google.com/apis/dashboard?project=${GOOGLE_CLOUD_PROJECT}"
  for api in "${GCP_APIS[@]}"; do note "  - $api"; done
  step "Click '+ Enable APIs and Services', search the API name, click Enable."
  warn "10 APIs, one search each — tedious. Install/authenticate gcloud and re-run this wizard to skip it."
  pause "Enabled all 10? Press Enter to continue."
}

if command -v gcloud >/dev/null 2>&1 \
  && confirm "gcloud detected — enable all 10 APIs for you now?"; then
  if gcloud services enable "${GCP_APIS[@]}" --project="$GOOGLE_CLOUD_PROJECT"; then
    note "APIs enabled via gcloud."
  else
    warn "gcloud failed (not authenticated? billing not linked?) — console it is."
    enable_apis_console
  fi
else
  enable_apis_console
fi

# ── Stage 4: OAuth consent screen ───────────────────────────────────────────
stage "OAuth consent screen — External, published to production"
say "This is what Google shows each user once, on first authorize."
open_url "https://console.cloud.google.com/auth/consent?project=${GOOGLE_CLOUD_PROJECT}"
step "Get started / Configure: User type = External → Create."
step "App name: e.g. Compose Yourself Assistant. User support email: yours."
step "Scopes: skip — the OAuth client requests them at consent time."
step "Publishing: click 'Publish app' → status becomes 'In production'."
warn "Leave it in 'Testing' and Google expires refresh tokens after 7 days — publish it."
note "Users will see a one-time 'Google hasn't verified this app' warning — expected;"
note "they click Advanced → Go to <app> (unsafe) once and never again."
pause "Consent screen configured and published? Press Enter to continue."

# ── Stage 5: Create the OAuth 2.0 client ───────────────────────────────────
stage "Create the OAuth 2.0 client (Web application)"
open_url "https://console.cloud.google.com/apis/credentials?project=${GOOGLE_CLOUD_PROJECT}"
step "Create Credentials → OAuth client ID → Application type: Web application."
step "Name: e.g. openwebui-mcp"
say "Authorized redirect URIs — add these 4 (copy each):"
note "  ${WEBUI_URL}/oauth/clients/mcp:google-gmail/callback"
note "  ${WEBUI_URL}/oauth/clients/mcp:google-calendar/callback"
note "  ${WEBUI_URL}/oauth/clients/mcp:google-docs/callback"
note "  ${WEBUI_URL}/oauth/clients/mcp:google-sheets/callback"
step "Click Create, then copy the Client ID."
ask GOOGLE_MCP_CLIENT_ID "Paste the Client ID:"
step "Copy the Client secret (click Copy on the dialog, or 'Show' later)."
ask_secret GOOGLE_MCP_CLIENT_SECRET "Paste the Client secret:"
write_env GOOGLE_MCP_CLIENT_ID "$GOOGLE_MCP_CLIENT_ID"
write_env GOOGLE_MCP_CLIENT_SECRET "$GOOGLE_MCP_CLIENT_SECRET"
note ""
note "If the later per-user authorize step ever fails with redirect_uri_mismatch,"
note "Google's error page shows the exact URI Open WebUI sent — add that URI to"
note "this client and retry."

# ── Stage 6: What happens next ─────────────────────────────────────────────
stage "Done — what happens next"
say "GCP side is complete. These 3 values feed the Open WebUI compose wiring"
say "(TOOL_SERVER_CONNECTIONS env + Fernet blob generation — separate work)."
say "After that wiring is deployed, each Open WebUI user clicks Authorize once"
say "per service; tokens persist per-user in the Open WebUI database."
note ""
say "If this .env isn't the deployment's, copy the 3 new values to"
say "sweetpantedlady:/opt/docker/composeyourself/.env"
pause "Press Enter to finish."

finish
